language: php
php:
  - '7.1'
  - '7.2'

env:
  - WITH_EXTENSIONS=1
  - WITH_EXTENSIONS=0
  - LOWEST="--prefer-stable --prefer-lowest"
  - LOWEST=""

before_script:
  - composer self-update
  - bash -c "if [ \"$WITH_EXTENSIONS\" == \"1\" ] ; then composer require --no-update beberlei/DoctrineExtensions; fi"
  - composer update $LOWEST
