language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

before_install:
  - pecl install -f ast-0.1.6

env:
  - WITH_EXTENSIONS=1
  - WITH_EXTENSIONS=0
  
before_script:
  - composer self-update
  - bash -c "if [ \"$WITH_EXTENSIONS\" == \"1\" ] ; then composer require --no-update beberlei/DoctrineExtensions; fi"
  - bash -c "if [ \"$WITH_EXTENSIONS\" == \"1\" ] ; then composer require --no-update phpoffice/phpspreadsheet:dev-master; fi"
  - composer install
