services:
    silvioq.report.dt:
        class: Silvioq\ReportBundle\Datatable\Builder
        factory: [ "@silvioq.report.datatable", "build" ]
        public: true

    silvioq.report.datatable:
        class: Silvioq\ReportBundle\Datatable\DatatableFactory
        arguments: ["@doctrine.orm.entity_manager", "@request_stack"]
        public: true
        
    silvioq.report.table:
        class: Silvioq\ReportBundle\Table\TableFactory
        public: true

    silvioq.report.table.doctrineloader:
        class: Silvioq\ReportBundle\Table\DefinitionLoader\DoctrineDefinitionLoader
        arguments: ["@doctrine.orm.entity_manager", "@annotation_reader"]
        public: false
        tags:
            - { name: 'silvioq.table.loader', priority: 0 }
