services:
    silvioq.report.dt:
        class: Silvioq\ReportBundle\Datatable\Builder
        factory: [ "@silvioq.report.datatable", "buildDatatable" ]
        public: true

    datatable:
        alias: "silvioq.report.dt"

    Silvioq\ReportBundle\Datatable\Builder:
        alias: "silvioq.report.dt"

    silvioq.report.datatable:
        class: Silvioq\ReportBundle\Datatable\DatatableFactory
        arguments: ["@doctrine.orm.entity_manager", "@request_stack"]
        public: false

    silvioq.report.table:
        class: Silvioq\ReportBundle\Table\TableFactory
        public: true

    silvioq.report.dt.condition:
        class: Silvioq\ReportBundle\Datatable\Condition\ConditionBuilder
        public: true
        arguments: ["@annotation_reader"]

    silvioq.report.table.doctrineloader:
        class: Silvioq\ReportBundle\Table\DefinitionLoader\DoctrineDefinitionLoader
        arguments: ["@doctrine.orm.entity_manager", "@annotation_reader"]
        public: false
        tags:
            - { name: 'silvioq.table.loader', priority: 0 }

    Silvioq\ReportBundle\Table\TableFactory:
        alias: "silvioq.report.table"

    Silvioq\ReportBundle\Datatable\Condition\ConditionBuilder:
        alias: "silvioq.report.dt.condition"
