services:
    silvioq.report.dt:
        class: Silvioq\ReportBundle\Datatable\Builder
        factory: [ "@silvioq.report.datatable", "build" ]
        public: true

    silvioq.report.datatable:
        class: Silvioq\ReportBundle\Service\DatatableFactory
        arguments: ["@doctrine.orm.entity_manager", "@request_stack"]
        public: true
        
    silvioq.report.table:
        class: Silvioq\ReportBundle\Table\TableFactory
        arguments: ["@doctrine.orm.entity_manager", "@annotation_reader"]
        public: true
